#!/bin/bash
#
# post-checkout-pbit: have git handle pbit files by deflating them and storing
#                      the files in the repository, not the zip file. 
#
#                      companion to pre-commit-pbit
#                      currently identical to post-commit

# -- config -- #
TMP_PREFIX='.~' # prefix unzipped directory--should NOT conflict with 
                   # anything in your repo

# -- end config -- #

echo
echo "=== Post-checkout PBIT processing ===="

# TODO might fail if "zip" command is not installed
repack_pbit () {
    # re-zip the XML directory 
    rm "$1"
    cd "${TMP_PREFIX}$1"
    zip "../$1" -r *
    cd ..
}

# make it easy to iterate over subdirectories
shopt -s globstar

# repack all the zipfiles
# TODO might make unpredictable results if no PBIT was commited
start_dir="$(pwd)"
for i in **/${TMP_PREFIX}*.pbit; do 
    dir=$(dirname "$i")
    base=$(basename "$i")
    file=${base:${#TMP_PREFIX}}
    cd "$dir"
    repack_pbit "$file"
    cd "$start_dir"
done

echo "=== End of post-checkout processing ==="
echo
